version: '1.0'
name: branch-pipeline
displayName: abgi打包
triggers:
  trigger: auto
  pr:
    branches:
      precise:
        - ginVue
stages:
  - name: stage-build
    displayName: 前后端打包
    strategy: naturally
    trigger: auto
    steps:
      - step: build@golang
        name: build_full
        displayName: abgi
        golangVersion: 1.23.11
        commands:
          - npm config set registry https://registry.npmmirror.com
          - cd web
          - npm install
          - npm run build
          - cd ..
          - export GOPROXY=https://goproxy.cn
          - go mod tidy
          - go build -o output/abgi ./...
        artifacts:
          - name: BACKEND_ARTIFACT
            path:
              - ./output
        caches:
          - ~/.npm
          - ~/.yarn
          - /go/pkg/mod
        strategy: {}
  - name: stage-upload
    displayName: 上传制品
    strategy: naturally
    trigger: auto
    steps:
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BACKEND_ARTIFACT
        artifactName: output
        strategy:
          retry: '0'
  - name: stage-release
    displayName: 发布
    strategy: naturally
    trigger: auto
    steps:
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: 发布
        dependArtifact: BACKEND_ARTIFACT
        version: 3.0.0.0
        autoIncrement: true
        strategy: {}
